research_task:
  description: >
    Conduct thorough research about {topic}. Identify emerging trends, analyze competitor
    strategies, and gather data-driven insights. Focus on finding interesting and relevant
    information considering the current year is 2024. Identify key performance indicators
    (KPIs) for potential content pieces and outline possible distribution channels.
  expected_output: >
    A list of 10 bullet points containing the most relevant information about {topic},
    including emerging trends, competitor strategies, and potential KPIs for content.
  agent: researcher

content_generation_task:
  description: >
    Based on the research provided, generate engaging and innovative content ideas for
    {topic} that align with {company}'s brand voice and target audience preferences.
    Produce outlines for a diverse range of content formats including blog posts,
    social media content, infographics, and video scripts.
  expected_output: >
    A detailed outline of at least 5 content pieces in various formats (blog post,
    social media content, infographic, video script, etc.) related to {topic}.
    Each outline should include a brief description, target audience, and potential
    distribution channels.
  agent: content_generator

create_advertisement_poster_task:
  description: >
    Create a visually appealing and effective advertisement poster for {company}'s
    {topic}. The poster should capture attention, communicate key messages clearly,
    and drive engagement with {company}'s target audience. Use the AdvertisementPosterTool
    to gather necessary information and generate the poster image.
  expected_output: >
    A high-quality advertisement poster image saved as a PNG file, along with a brief
    explanation of the design choices made and how they align with {company}'s brand
    and target audience.
  agent: marketing_designer

analyze_marketing_performance_task:
  description: >
    Analyze marketing performance data for {company}'s {topic} across different platforms.
    Identify trends, compare metrics like CTR, CPC, and ROI, and provide actionable
    insights to optimize marketing strategies. Use the AdsAnalyticsTool to retrieve
    performance data and the BudgetAllocatorTool to recommend budget allocations.
  expected_output: >
    A comprehensive analysis of marketing performance across platforms, including
    key metrics, trends, and recommendations for budget allocation and strategy
    optimization.
  agent: marketing_analyst

manage_social_media_task:
  description: >
    Manage {company}'s social media presence for {topic}. Schedule posts at optimal
    times using the PostSchedulerTool, monitor and respond to comments using the
    SocialCommentMonitorTool, and maintain a consistent brand voice across all
    platforms.
  expected_output: >
    A social media management report including scheduled posts, comment responses,
    and recommendations for improving engagement and reach.
  agent: social_media_manager
